services:
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sensor_data
      TZ: Europe/Rome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  main:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 main.py
    privileged: true  # Aggiungi questa riga
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  # Monta la porta seriale
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=sensor_data
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - TZ=Europe/Rome
    restart: unless-stopped

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
      - main
    environment:
      - DB_HOST=db
      - DB_DATABASE=sensor_data
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - TZ=Europe/Rome
    restart: unless-stopped

  network_scanner:
    build:
      context: ./src  # Assumi che scanner.py si trovi in questa directory
      dockerfile: Dockerfile
    command: python3 scanner.py
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=sensor_data
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - TZ=Europe/Rome
    restart: unless-stopped

volumes:
  postgres_data:
