services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sensor_data
      TZ: Europe/Rome
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  main:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 main.py
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=sensor_data
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - TZ=Europe/Rome
    restart: unless-stopped

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
      - main
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/
      - DB_HOST=db
      - DB_DATABASE=sensor_data
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - TZ=Europe/Rome
    volumes:
      - ./src/backup.sh:/usr/local/bin/backup.sh
      - ./backup:/backup  # Monta la cartella di backup nella directory del contenitore
      - ./src/static:/app/static
    restart: unless-stopped

  network_scanner:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 scanner.py
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=sensor_data
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - TZ=Europe/Rome
    restart: unless-stopped

volumes:
  postgres_data:
  mongo-data:
